import { useEffect, useState } from 'preact/hooks';
import type { Account, ParsedImport } from '../lib/domain/types';
import type { ImportCommitResult } from '../lib/db';
import { addAccount, commitCsv, loadAccounts, previewCsv } from './dataClient';

export default function ImportWizard() {
  const [accounts,setAccounts]=useState<Account[]>([]); const [accountId,setAccountId]=useState(''); const [creating,setCreating]=useState(false); const [file,setFile]=useState<File>(); const [parsed,setParsed]=useState<ParsedImport>(); const [parsedAccount,setParsedAccount]=useState<Account>(); const [step,setStep]=useState(1); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [result,setResult]=useState<ImportCommitResult>();
  const [form,setForm]=useState({label:'Exness utama',accountNumber:'',server:'',currency:'USD',sourceTimeZone:Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'});
  useEffect(()=>{loadAccounts().then(a=>{setAccounts(a);setAccountId(a[0]?.id??'');setCreating(!a.length)}).catch(()=>setError('Database lokal tidak dapat dibuka.'));},[]);
  const account=accounts.find(a=>a.id===accountId);
  async function ensureAccount(){ if(account)return account; const made=await addAccount(form); setAccounts(a=>[...a,made]);setAccountId(made.id);setCreating(false);return made; }
  async function handlePreview(){if(!file)return;setBusy(true);setError('');try{const a=await ensureAccount();setParsedAccount(a);setParsed(await previewCsv(file,a));setStep(3)}catch(e){setError(e instanceof Error?e.message:'CSV tidak dapat dibaca.')}finally{setBusy(false)}}
  async function commit(){if(!parsed||!file||!parsedAccount)return;setBusy(true);setError('');try{setResult(await commitCsv(parsed,parsedAccount,file.name));setStep(4)}catch(e){setError(e instanceof Error?e.message:'Import gagal disimpan.')}finally{setBusy(false)}}
  return <section className="card">
    <div className="stepper">{['Account','File CSV','Review','Selesai'].map((x,i)=><div className={`step ${step===i+1?'active':step>i+1?'done':''}`} key={x}><span className="step-number">{step>i+1?'✓':i+1}</span><span>{x}</span></div>)}</div>
    {error&&<div className="notice error" role="alert">{error}</div>}
    {step===1&&<div className="grid" style={{maxWidth:650}}>{accounts.length>0&&<div className="field"><label>Trading account</label><select value={creating?'new':accountId} onChange={e=>e.currentTarget.value==='new'?setCreating(true):(setCreating(false),setAccountId(e.currentTarget.value))}>{accounts.map(a=><option value={a.id} key={a.id}>{a.label} · {a.accountNumber}</option>)}<option value="new">+ Buat account baru</option></select></div>}{creating&&<div className="form-grid"><Field label="Label" value={form.label} onChange={v=>setForm({...form,label:v})}/><Field label="Nomor account" value={form.accountNumber} onChange={v=>setForm({...form,accountNumber:v})}/><Field label="Server (opsional)" value={form.server} onChange={v=>setForm({...form,server:v})}/><Field label="Currency" value={form.currency} onChange={v=>setForm({...form,currency:v.toUpperCase()})}/><Field label="Source timezone" value={form.sourceTimeZone} onChange={v=>setForm({...form,sourceTimeZone:v})}/></div>}<div className="actions"><button className="btn primary" disabled={creating&&(!form.accountNumber||!form.label||!form.currency)} onClick={()=>setStep(2)}>Lanjut pilih file →</button></div></div>}
    {step===2&&<div className="grid"><label className="dropzone"><input type="file" accept=".csv,text/csv" hidden onChange={e=>setFile(e.currentTarget.files?.[0])}/><div><div className="empty-icon" style={{margin:'0 auto 14px'}}>⇧</div><h3>{file?.name??'Pilih file CSV Exness'}</h3><p className="muted">Klik untuk memilih file. Data diproses lokal dan tidak diunggah ke server.</p>{file&&<span className="badge">{(file.size/1024).toFixed(1)} KB</span>}</div></label><div className="actions"><button className="btn" onClick={()=>setStep(1)}>← Kembali</button><button className="btn primary" disabled={!file||busy} onClick={handlePreview}>{busy?'Membaca…':'Preview CSV →'}</button></div></div>}
    {step===3&&parsed&&<div className="grid"><div className="grid three-col"><Mini label="Deal valid" value={parsed.deals.length}/><Mini label="Balance event" value={parsed.balanceEvents.length}/><Mini label="Issue" value={parsed.issues.length}/></div>{parsed.issues.length>0&&<div className="notice warning">{parsed.issues.slice(0,5).map(x=><div key={`${x.row}-${x.message}`}>Baris {x.row}: {x.message}</div>)}</div>}<div className="table-wrap" style={{margin:0}}><table><thead><tr>{Object.keys(parsed.preview[0]??{}).slice(0,6).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{parsed.preview.slice(0,5).map((r,i)=><tr key={i}>{Object.values(r).slice(0,6).map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div><div className="actions"><button className="btn" onClick={()=>setStep(2)}>← Ganti file</button><button className="btn primary" disabled={busy} onClick={commit}>{busy?'Menyimpan…':'Simpan import'}</button></div></div>}
    {step===4&&<div className="empty"><div className="empty-icon">✓</div><h3>{result?.alreadyImported?'File sudah pernah diimpor':'Import selesai'}</h3><p>{result?.inserted??0} data baru, {result?.duplicates??0} duplikat, dan {result?.failed??0} gagal.</p><div className="actions"><a className="btn primary" href={`${import.meta.env.BASE_URL}trades/`}>Lihat trades</a><button className="btn" onClick={()=>{setFile(undefined);setParsed(undefined);setParsedAccount(undefined);setResult(undefined);setStep(2)}}>Import lagi</button></div></div>}
  </section>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div className="field"><label>{label}</label><input aria-label={label} value={value} onInput={e=>onChange(e.currentTarget.value)}/></div>}
function Mini({label,value}:{label:string;value:number}){return <div className="card"><div className="stat-label">{label}</div><div className="stat-value">{value}</div></div>}
