import { useEffect, useRef, useState } from 'react';
import type { Deal, Journal, Position } from '../lib/domain/types';
import { SideBadge } from './ui';
import { loadPositionBundle, saveJournal } from './dataClient';

const blank = (positionId:string): Journal => ({id:crypto.randomUUID(),positionId,strategy:'',setup:'',thesis:'',emotion:'',mistakes:[],tags:[],review:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
export default function JournalApp(){
  const [position,setPosition]=useState<Position>(); const [deals,setDeals]=useState<Deal[]>([]); const [journal,setJournal]=useState<Journal>(); const [state,setState]=useState<'loading'|'idle'|'saving'|'saved'|'error'>('loading'); const [id,setId]=useState<string>(); const ready=useRef(false);
  useEffect(()=>setId(new URLSearchParams(window.location.search).get('positionId')??''),[]);
  useEffect(()=>{if(id===undefined)return;if(!id){setState('idle');return;}loadPositionBundle(id).then(b=>{setPosition(b.position);setDeals(b.deals);setJournal(b.journal??blank(id));setState('idle');setTimeout(()=>{ready.current=true},0)}).catch(()=>setState('error'))},[id]);
  useEffect(()=>{if(!journal||!ready.current)return;setState('saving');const timer=setTimeout(()=>saveJournal({...journal,updatedAt:new Date().toISOString()}).then(()=>setState('saved')).catch(()=>setState('error')),650);return()=>clearTimeout(timer)},[journal]);
  if(state==='loading')return <div className="card"><div className="skeleton" style={{height:360}}/></div>;
  if(!id)return <div className="empty card"><div className="empty-icon">✎</div><h3>Pilih trade untuk dijurnal</h3><p>Buka daftar trades, lalu pilih “Isi jurnal” pada posisi yang ingin dievaluasi.</p><a className="btn primary" href={`${import.meta.env.BASE_URL}trades/`}>Buka trades</a></div>;
  if(!position||!journal)return <div className="notice error">Posisi tidak ditemukan. Trade mungkin sudah terhapus atau ID tidak valid.</div>;
  const update=<K extends keyof Journal>(key:K,value:Journal[K])=>setJournal(j=>j?{...j,[key]:value}:j); const net=Number(position.netProfit); const risk=Number(journal.riskAmount||0); const realized=risk?net/risk:null;
  return <div className="grid two-col">
    <div className="grid">
      <section className="card"><div className="card-head"><div><SideBadge side={position.side} /><h2 style={{fontSize:24,margin:'6px 0 0'}}>{position.symbol}</h2></div><div style={{textAlign:'right'}}><div className={`stat-value ${net>=0?'profit':'loss'}`} style={{fontSize:22,margin:0}}>{net.toFixed(2)}</div><span className="muted" style={{fontSize:11}}>Net P&amp;L</span></div></div><div className="grid three-col"><Fact label="Open" value={new Date(position.openAt).toLocaleString('id-ID')}/><Fact label="Close" value={position.closeAt?new Date(position.closeAt).toLocaleString('id-ID'):'Masih terbuka'}/><Fact label="Volume" value={position.volume}/><Fact label="Entry avg." value={position.averageOpenPrice}/><Fact label="Exit avg." value={position.averageClosePrice}/><Fact label="Realized R" value={realized===null?'—':`${realized.toFixed(2)}R`}/></div></section>
      <section className="card"><div className="card-head"><h2>Catatan evaluasi</h2><span className={`save-state ${state==='error'?'loss':''}`}>{state==='saving'?'Menyimpan…':state==='saved'?'✓ Tersimpan':state==='error'?'Gagal menyimpan':'Autosave aktif'}</span></div><div className="form-grid"><Text label="Strategy" value={journal.strategy} set={v=>update('strategy',v)}/><Text label="Setup" value={journal.setup} set={v=>update('setup',v)}/><Text label="Emotion" value={journal.emotion} set={v=>update('emotion',v)}/><Text label="Rating eksekusi (1–5)" type="number" value={journal.executionRating?.toString()??''} set={v=>update('executionRating',v?Math.min(5,Math.max(1,Number(v))):undefined)}/><Text label="Risk amount" type="number" value={journal.riskAmount??''} set={v=>update('riskAmount',v||undefined)}/><Text label="Planned R:R" type="number" value={journal.plannedRiskReward??''} set={v=>update('plannedRiskReward',v||undefined)}/><Text label="Tags (pisahkan koma)" value={journal.tags.join(', ')} set={v=>update('tags',split(v))}/><Text label="Mistakes (pisahkan koma)" value={journal.mistakes.join(', ')} set={v=>update('mistakes',split(v))}/><Area label="Thesis / alasan entry" value={journal.thesis} set={v=>update('thesis',v)}/><Area label="Review setelah trade" value={journal.review} set={v=>update('review',v)}/></div></section>
    </div>
    <section className="card"><div className="card-head"><h2>Rincian deal</h2><span className="badge">{deals.length} deal</span></div>{!deals.length?<div className="empty" style={{minHeight:180}}><p>Deal sumber tidak ditemukan.</p></div>:<div className="table-wrap"><table><thead><tr><th>Waktu</th><th>Event</th><th>Vol.</th><th>Harga</th><th>P&amp;L</th></tr></thead><tbody>{deals.map(d=><tr key={d.id}><td>{new Date(d.occurredAt).toLocaleString('id-ID')}</td><td>{d.event}</td><td>{d.volume}</td><td>{d.price}</td><td className={Number(d.profit)>=0?'profit':'loss'}>{d.profit}</td></tr>)}</tbody></table></div>}</section>
  </div>
}
const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
function Fact({label,value}:{label:string;value:string}){return <div><div className="stat-label">{label}</div><strong style={{display:'block',marginTop:6,fontSize:12}}>{value}</strong></div>}
function Text({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <div className="field"><label>{label}</label><input aria-label={label} type={type} value={value} onChange={e=>set(e.target.value)}/></div>}
function Area({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <div className="field span-2"><label>{label}</label><textarea aria-label={label} value={value} onChange={e=>set(e.target.value)}/></div>}
