import { useEffect, useState } from 'react';
import type { Account, ThemePreference } from '../lib/domain/types';
import { createPlainBackup, decryptBackup, encryptBackup, parsePlainBackup, type BackupSnapshot } from '../lib/backup';
import { THEME_STORAGE_KEY, applyTheme, getThemePreference } from '../lib/theme';
import MarketSettings from './MarketSettings';
import { clearLocalData, loadAccounts, loadAppSettings, loadSnapshot, restoreSnapshot, saveThemePreference } from './dataClient';

const download = (text: string, name: string) => { const url = URL.createObjectURL(new Blob([text], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); };

export default function SettingsApp() {
  // The static HTML ships these controls fully formed, but their handlers
  // only exist once this island hydrates. Without this gate a click landing
  // in that window changes the radio visually and does nothing else.
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => { setHydrated(true); }, []);
  const [accounts,setAccounts] = useState<Account[]>([]); const [preference,setPreference] = useState<ThemePreference>(() => getThemePreference()); const [password,setPassword] = useState(''); const [message,setMessage] = useState(''); const [error,setError] = useState(''); const [restore,setRestore] = useState<{snapshot:BackupSnapshot;name:string}>(); const [busy,setBusy] = useState(false);
  useEffect(() => { Promise.all([loadAccounts(),loadAppSettings()]).then(([savedAccounts,settings]) => { setAccounts(savedAccounts); setPreference(settings.theme); if (!localStorage.getItem(THEME_STORAGE_KEY)) applyTheme(settings.theme); }).catch(() => undefined); }, []);
  const run = async (action: () => Promise<void>) => { setBusy(true); setError(''); setMessage(''); try { await action(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Operasi gagal.'); } finally { setBusy(false); } };
  const updateTheme = async (next: ThemePreference) => { setPreference(next); applyTheme(next); await saveThemePreference(next); setMessage('Preferensi tema disimpan.'); };
  const exportData = (encrypted: boolean) => run(async () => { const snapshot = await loadSnapshot(); const stamp = new Date().toISOString().slice(0,10); if (encrypted) { if (!password) throw new Error('Masukkan password untuk backup terenkripsi.'); download(await encryptBackup(snapshot,password),`feriktrading-${stamp}.ftj.enc.json`); } else download(createPlainBackup(snapshot),`feriktrading-${stamp}.ftj.json`); setMessage('Backup berhasil dibuat. Simpan file di tempat yang aman.'); });
  const inspect = (file?: File) => run(async () => { if (!file) return; const raw = await file.text(); const snapshot = file.name.endsWith('.enc.json') ? await decryptBackup(raw,password) : parsePlainBackup(raw); setRestore({snapshot,name:file.name}); });
  const restoreData = (mode: 'merge' | 'replace') => run(async () => { if (!restore) return; await restoreSnapshot(restore.snapshot,mode); const settings = await loadAppSettings(); setPreference(settings.theme); applyTheme(settings.theme); setRestore(undefined); setMessage(`Restore ${mode} berhasil.`); setAccounts(await loadAccounts()); });
  return <div className="grid two-col"><div className="grid">
    <section className="card settings-section"><div className="card-head"><h2>Tampilan</h2><span className="badge">Tema</span></div><p className="subtitle">System mengikuti pengaturan terang/gelap perangkat. Pilihan ini juga ikut tersimpan dalam backup.</p><fieldset className="theme-options"><legend>Pilihan tema</legend>{([['system','System'],['light','Light'],['dark','Dark']] as const).map(([value,label]) => <label className={`theme-option ${preference === value ? 'selected' : ''}`} key={value}><input type="radio" name="theme" value={value} checked={preference===value} disabled={!hydrated} onChange={() => updateTheme(value)} /><span><strong>{label}</strong><small>{value === 'system' ? 'Ikuti perangkat' : value === 'light' ? 'Latar terang untuk siang hari' : 'Latar gelap untuk sesi fokus'}</small></span></label>)}</fieldset></section>
    <section className="card settings-section"><div className="card-head"><h2>Trading accounts</h2><span className="badge">{accounts.length}</span></div>{accounts.length?<div className="metric-list">{accounts.map(account=><div className="metric-row" key={account.id}><span><strong className="metric-emphasis">{account.label}</strong><br/>{account.accountNumber} · MT5</span><strong>{account.currency}</strong></div>)}</div>:<div className="empty compact"><p>Account dibuat ketika melakukan import pertama.</p></div>}<a className="btn" href={`${import.meta.env.BASE_URL}import/`}>Tambah melalui import</a></section>
    <section className="card settings-section"><div className="card-head"><h2>Export backup</h2><span className="badge">Local file</span></div><p className="subtitle">Backup mencakup account, data broker, journal, dan pengaturan.</p><div className="field spaced"><label>Password enkripsi</label><input aria-label="Password enkripsi" type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="Hanya untuk backup terenkripsi"/></div><div className="actions"><button className="btn" disabled={busy} onClick={()=>exportData(false)}>Export plain</button><button className="btn primary" disabled={busy||!password} onClick={()=>exportData(true)}>Export encrypted</button></div></section>
  </div><div className="grid">
    <MarketSettings />
    <section className="card settings-section"><div className="card-head"><h2>Restore backup</h2></div><p className="subtitle">Untuk file encrypted, masukkan password yang dipakai saat export sebelum memilih file.</p><label className="dropzone compact-dropzone"><input aria-label="Pilih file backup" hidden type="file" accept=".json" onChange={event=>inspect(event.target.files?.[0])}/><div><div className="empty-icon">⇩</div><strong>Pilih file backup</strong></div></label>{restore&&<div className="notice restore-preview"><strong>{restore.name}</strong><br/>{restore.snapshot.accounts.length} account · {restore.snapshot.positions.length} posisi<div className="actions"><button className="btn" onClick={()=>restoreData('merge')}>Merge</button><button className="btn danger" onClick={()=>restoreData('replace')}>Replace semua</button></div></div>}</section>
    <section className="card settings-section"><div className="card-head"><h2>Privasi & penyimpanan</h2></div><div className="notice">Semua data berada di IndexedDB browser ini. Membersihkan site data dapat menghapus jurnal secara permanen.</div><button className="btn danger spaced-top" disabled={busy} onClick={()=>{if(confirm('Hapus seluruh data lokal? Tindakan ini tidak dapat dibatalkan.'))run(async()=>{await clearLocalData();setAccounts([]);setMessage('Semua data lokal telah dihapus.');});}}>Hapus semua data lokal</button></section>
    {(message||error)&&<div className={`notice ${error?'error':'success'}`} role="status">{error||message}</div>}
  </div></div>;
}
